version: "3.8"
services:
  localstack:
    image: localstack/localstack:3.8.0
    container_name: ephemeralguard-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,s3,dynamodb,iam,cloudtrail,sts,logs,kms
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
